### ISSUE TITLE
Issue with request sending

### ISSUE THREAD

**Issue by SonyKar** [becoming/01-java-notification-service#1]
The problem is that everything was perfectly compiled, but if you send a POST request through PostMan, you will receive an error

![image](https://user-images.githubusercontent.com/42860126/56350006-737b5600-61d2-11e9-83e7-1aef11856164.png)

**Comment by rodislav** [comment]
There's a bug in the video, I'll fix it this weekend and will re-upload it.
For now what you have to do it to open the Body tab, select the option: raw and describe a email request in json format.

**Comment by SonyKar** [comment]
Yay, I have done it. I think to add a little explanatory screenshot will be enough, you do not have to redo video again:3
Or you can just expand you video, by adding to id explanation part to the end of the video and to put an explanatory label in YouTube

**Comment by rodislav** [comment]
I've changed the video, so that it mentions the body of the request
https://youtu.be/9iGJXNwGFqI?t=630

**Comment by SonyKar** [comment]
Yep, it all works, thanks:)
