### ISSUE TITLE
BUG(create services

### ISSUE THREAD

**Issue by snowtoslow** [becoming/01-java-notification-service#5]
I start to write the SERVICE part of the application and I faced a problem:

1)When I wanna check is my app is working I receive smth like this:

      "timestamp":"2019-08-05T10:53:50.372+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/email" 

2)When I look in InteliJ it tell me that the problem is: 
      Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

and it tell me that the problem is in (EmailController.java:15). 

3)When I try to debugg it it say me that ID is null;

I will attach the code to this issue and I will add a prtScrn of POSTMAN
![POSTMAN1](https://user-images.githubusercontent.com/47230162/62460865-d3026f00-b78b-11e9-8c86-9f8d7cd22a88.png)

4)Here is result of debbuging:
(![DEBUGG](https://user-images.githubusercontent.com/47230162/62460938-13fa8380-b78c-11e9-8fbc-aaa0bc0aab5a.png))

****My Reposirtory:
[]https://github.com/snowtoslow/java-notification-service/tree/master/src/main/java/md/snowtoslow/notificationservice

**Comment by rodislav** [comment]
You need to add the constructor for the controller, so that spring can inject one instance of the service, e.g. https://github.com/becoming/01-java-notification-service/blob/master/src/main/java/tech/becoming/notificationservice/controller/EmailController.java#L19
